### PR TITLE
IEx strategy

### LINKED ISSUE #12: Is it possible to run tests in IEx shell and then analyze the results for neotest?
First of all, thank you very much for your work, which has given me a new experience in testing elixir in nvim. But I don't know if you have the same feeling that doing Unit Testing in elixir is much slower than in other languages, I know it's not caused by neotest or Lua.

The main reason is that every time you run a `mix test` you need to start the whole app, whereas if we just run the test in `iex`, it would be much faster.

Here is a project I generated with `mix new elixir_demo`, you can see that even the simplest project that is brand new takes `1.5` seconds to run each test using the command line, whereas with iex it just takes `0.015` seconds, which is a **100x** improvement, and if we could do that, then developing elixir projects in Nvim would be a superb experience.

image

### References:

* ExUnit tests from a module instead of command line/mix - Questions / Help - Elixir Programming Language Forum
https://elixirforum.com/t/exunit-tests-from-a-module-instead-of-command-line-mix/22485
* TestIex — Easier Test Driven Development in Elixir | by Daniel Olshansky | Medium
https://olshansky.medium.com/testiex-easier-test-driven-development-in-elixir-761cd1a9f11
* How to speed up the start of `mix test`? - Questions / Help - Elixir Programming Language Forum
https://elixirforum.com/t/how-to-speed-up-the-start-of-mix-test/43498/15

### PR DESCRIPTION
**Pull request by jfpedroza**
Adds a strategy for running tests in the same OS process every time.

The first time a test is run, the process starts. From there, other runs communicate with the same process.

Still WIP, but mostly complete.

Closes #12

### CODE REVIEW

**Comment by scottming** [comment]
image

I found a small bug that won't clear past test result records, above contains 4 times records.

**Comment by scottming** [comment]
Another small bug is that the output cannot be displayed when the test passes. The left side is the result of `iex` test, the right side is the result of `mix test`

image

**Comment by scottming** [comment]
Also, does this strategy require the project to rely on `{:ex_unit_notifier, "~> 1.2", only: :test}`?

image

**Comment by scottming** [comment]
Running the test on the summary tree(by key `r`), it seems that the strategy used is still `mix test`:

image

**Comment by scottming** [comment]
Finally, I would like to say that the speed really Awesome.

**Comment by jfpedroza** [comment]
> I found a small bug that won't clear past test result records, above contains 4 times records.

Got it, should be easy to fix.

> Another small bug is that the output cannot be displayed when the test passes. The left side is the result of iex test, the right side is the result of mix test

This is not related to this PR. It's because there is no output for successful tests. Maybe it could be set to something like "Test passed in 50ms".

> Also, does this strategy require the project to rely on {:ex_unit_notifier, "~> 1.2", only: :test}?

No, if you are seeing that error, it is because you have that formatter listed in `extra_formatters`.

> Running the test on the summary tree(by key r), it seems that the strategy used is still mix test:

The summary doesn't support specifying the strategy. You probably need to change the default strategy for the project in `neotest.setup_project()`. If you do, you won't need to pass it anymore in `neotest.run.run()` either.

**Comment by jfpedroza** [comment]
@scottming Just fixed the two reported issues.

**Comment by scottming** [comment]
hi, Jhon, seems like the strategy field does not work in the setup.

```lua
		require("neotest-elixir")({
			args = { "--trace" },
      strategy = "iex",
		}),
```

but this `lua require('neotest').run.run({strategy = 'iex'})` config will works

**Comment by jfpedroza** [comment]
> seems like the strategy field does not work in the setup.

Wrong place. It's a setting of the project in Neotest, not of the adapter.

```lua
require("neotest").setup_project(vim.loop.cwd(), {
  adapters = {...},
  default_strategy = "iex"
})
```

**Comment by scottming** [comment]
~still not work~

```
require("neotest").setup_project(vim.loop.cwd(), {
	adapters = { require("neotest-elixir") },
	default_strategy = "iex",
})
```

~seems like this line does not send the project `strategy` to the client~

~https://github.com/nvim-neotest/neotest/blob/master/lua/neotest/client/runner.lua#L64~

  ~`args = vim.tbl_extend("keep", args or {}, { strategy = config.default_strategy })`~

fixed here: https://github.com/nvim-neotest/neotest/commit/fbd806c92e4486f56926837541532c93ab8dcd0f

**Comment by scottming** [comment]
Another usage scenario we need to consider is that sometimes the loop of the `iex` strategy will hang, so we need to provide a function to end the process.

Currently `lua require('neotest').run.stop()` does not work


This problem can be reproduced when you type `r` at the file cursor of the side tree.

image

**Comment by scottming** [comment]
Another bug is that if a test running in the sidebar encounters an error, the whole process crashes.

image

**Pull request closed without merging**
